### ISSUE TITLE
Enable ginkgo as alternative test runner

### ISSUE THREAD

**Issue by Nuckal777** [sapcc/go-makefile-maker#144]
When using ginkgo for writing tests it is recommended to run the with the [Ginkgo CLI](https://onsi.github.io/ginkgo/#ginkgo-cli-overview). A recommended configuration for running test as part of a CI pipeline is given [here](https://onsi.github.io/ginkgo/#recommended-continuous-integration-configuration).

**Comment by SuperSandro2000** [comment]
Is it safe to assume that gingko should be used when it is a direct dependency in go.mod or do we need another option for it?

**Comment by Nuckal777** [comment]
> Is it safe to assume that gingko should be used when it is a direct dependency in go.mod

Think so.
