### ISSUE TITLE
go specification in go mod requires 1.22.0 syntax now

### ISSUE THREAD

**Issue by notque** [sapcc/go-makefile-maker#159]
from 1.22 to 1.22.0 - code scanning (CodeQL) says 

"As of Go 1.21, toolchain versions must use the 1.N.P syntax.

1.22 in go.mod does not match this syntax and there is no additional toolchain directive, which may cause some go commands to fail."

**Comment by majewsky** [comment]
Yeah, we know, and we disagree. Using a three-numbered toolchain version makes builds fail locally if you run even a single dot release different. It's ridiculous. We will reevalulate with 1.23 which will reportedly fix some of this mess.
