### ISSUE TITLE
Toolchain trouble with Go Version in go.mod 

### ISSUE THREAD

**Issue by IvoGoman** [sapcc/go-makefile-maker#163]
I am having trouble with the `go 1.22` directive in the go.mod file generated.
The incomplete semantic version of GO in go.mod does not work with `GOTOOLCHAIN=auto`.
The behavior is explained here: https://go.dev/doc/toolchain#select. Problem being that with auto the go.mod file is consulted and go1.22 is not a valid go version.

E.g.
```bash
GOTOOLCHAIN=auto go env 
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available

GOTOOLCHAIN=local go env
GO111MODULE=''
GOARCH='arm64'
...
```
Having `GOTOOLCHAIN=auto` and `go 1.22.0` in the go.mod file also works.

Would it be possible to use the full semantic version in the `go.mod` file?

**Comment by majewsky** [comment]
Answered in #159:

> Yeah, we know, and we disagree. Using a three-numbered toolchain version makes builds fail locally if you run even a single dot release different. It's ridiculous. We will reevalulate with 1.23 which will reportedly fix some of this mess.

**Comment by IvoGoman** [comment]
That is part of the reason why I would like to use the auto. Then go will get the toolchain it requires and should not fail. https://go.dev/doc/toolchain#download

**Comment by majewsky** [comment]
I got an email that you made a different comment, but the comment does not seem to be here anymore. But just to make it explicit, we don't want to support `GOTOOLCHAIN=auto` because we generally don't like having tools download random shit. (Similar reason to why we prefer vendoring of dependency libs.)

**Comment by IvoGoman** [comment]
> I got an email that you made another comment, but the comment does not seem to be here anymore. But just to make it explicit, we don't want to support `GOTOOLCHAIN=auto` because we generally don't like having tools download random shit. (Similar reason to why we prefer vendoring of dependency libs.)
When reading through my comment again I considered it wrong. I remembered some implications with the three-numbered version as our internal pipelines that work on a pinned minor version with toolchain local. (where I did have the issue you mentioned)
